### PR TITLE
Setup the CODEOWNERS for pull request reviews

### PR DESCRIPTION
**Pull request by jimmyjames**

### CODE REVIEW

**Comment by damieng** [comment]
Needs revising once we've figured out new primary/secondary.

**Comment by davidpatrick** [comment]
I can be put down as primary

**Comment by jimmyjames** [comment]
Who should be secondary? If there's nobody identified I'm willing to do secondary

**Comment by jimmyjames** [comment]
> Who should be secondary? If there's nobody identified I'm willing to do secondary

@davidpatrick primary, myself secondary. New commit pushed to reflect in `CODEOWNERS` file.

**Pull request merged**
